### ISSUE TITLE
If a video is playing and is on autoplay when you navigate away from a page, the video starts to play again in the background of the page even though you can't see it

### ISSUE THREAD

**Issue by jasonfb** [hotwired/turbo-rails#147]
**Rails 6.1.3**
**Turbo-rails 0.5.9**

##  background

1. You must have a video on your  page that is set to `autoplay: :autoplay`
2. you will note that autoplay doesn't truly work in all browsers (if you *land* on a page with an autoplay video, chrome will ignore the instruction and the video will not autoplay for the benefit of the user's experience). However, a video can be played programmatically (via Javascript or an autoplay setting) after any user click, including any clicks originated from a Turbo-rails click
3. for this reason, if you arrive at a page through turbo-rails that has an autoplay video, the video bypasses Chrome's normal behavior and starts playing immediately. (I did not recreate a demo of this— but this is a 🎉  that should be kept!)
4. However, if you *navigate away* from a page where a video is playing that has autoplay set to true, the video mysteriously starts to play again on the new page (in the background-- you can't see it but you can hear it).

## Steps to reproduce
pull the reproduction app here: https://github.com/jasonfb/TR004

1. go to http://127.0.0.1:3000/
![Screen Shot 2021-03-13 at 6 54 50 PM](https://user-images.githubusercontent.com/59002/111052930-9f8aca80-842d-11eb-9554-3572070eebfb.png)

2. *start the video yourself using the play button*
![Screen Shot 2021-03-13 at 6 56 16 PM 2021-03-13 18-56-41](https://user-images.githubusercontent.com/59002/111052977-fabcbd00-842d-11eb-8b9c-b9ee21a39239.png)

(hey check out the nifty turbo-rails teaser I made)

3. Click the "Lets Go>>>" link, noticing that it is handled by Turbo

![Screen Shot 2021-03-13 at 6 56 16 PM 2021-03-13 18-58-36](https://user-images.githubusercontent.com/59002/111053003-32c40000-842e-11eb-968e-d0f1cbc47009.png)

4. when you get to my 'checkout', you can't see my video but you can hear the sound of it in the background.

and finally…
![Screen Shot 2021-03-13 at 6 59 21 PM](https://user-images.githubusercontent.com/59002/111053016-5129fb80-842e-11eb-81db-eeb4b0bcf621.png)

respectfully submitted, 
Jason

**Comment by jasonfb** [comment]
since it happens on all links and all page transitions, the impact is large. it will occur for any website with a video that has `autoplay: :autoplay`, and you see the symptom after you visit a page with that video. Once you navigate anywhere else to any other page, that video starts to play again in the background.

**Comment by jasonfb** [comment]
TEMPORARY FIX:

Don't use `autoplay="autoplay"`

*take important note:*
Turbo effectively eliminates Chrome's natural behavior to **_not_** autoplay when you browse from one page on your site to another (the way a normal link would work). This means you still cannot autoplay a video on the first page the user lands on, but will be able to effectively make the video start playing immediately anytime they click, including a navigate to another page.  You will need to orchestrate the playing by accessing the video element directly and calling `.play()` or `.pause()`

**Comment by seanpdoyle** [comment]
Was this issue resolved by https://github.com/hotwired/turbo/pull/226?

**Comment by rexblack** [comment]
Thanks so much, @jasonfb. This is how it can be fixed. Might well be that Turbo can't really do anything about it. However, I guess, it should at least be mentioned in the docs. Though, still wondering why Turbolinks hasn't got this one

**Comment by mattbenscho** [comment]
Can confirm that the issue is still present with turbo 1.4.0, rails 7.0.6 and ruby 3.2.2.

**Comment by fabiode** [comment]
confirming still happens with turbo 1.4.0, rails 7.0.8 and ruby 3.2.2

**Comment by dreamingtulpa** [comment]
Still happening with turbo-rails 2.0.4 / @hotwired/turbo-rails 8.0.3.

At least it helps to share some fun "[bug material](https://twitter.com/dreamingtulpa/status/1765658475441328448)" 😅

**Comment by seanpdoyle** [comment]
@jorgemanrubia could we re-open this issue?

**Comment by marckohlbrugge** [comment]
Still an in issue in `@hotwired/turbo-rails 8.0.4` – I was able to consistently reproduce it as follows:

```html
<video autoplay loop muted playsinline>
  <source src="path-to-your-video.mp4" type="video/mp4">
</video>
```

When this page is first loaded in **Firefox**, this video will autoplay, muted as expected.

However, when you **browse away** from the page, it suddenly starts playing again and this time **unmuted**.

Autoplaying videos are quite common these days and aren't really a nuisance when muted. They are also used as a more performant alternative to animated GIFs in which case there's no audio, but they still shouldn't be autoplayed in the background on a page that doesn't even include the <video> tag.

**Comment by Sprachprofi** [comment]
Having the same issue :( Please fix!

**Comment by Sprachprofi** [comment]
I'm guessing there is a problem with incorrect Turboframe replacement of content, because how else would it get the idea to play a video that is no longer present in the HTML...

**Comment by marckohlbrugge** [comment]
@Sprachprofi It's a bug in Turbo Drive, not Turbo Frames. Likely has something to do with the fact that with Turbo Drive the browser doesn't actually navigate away from the page, but uses Javascript to move some DOM around giving the illusion you're browsing to a new page. Part of this is that `<video>` elements don't get fully flushed out.

**Comment by mattbenscho** [comment]
It seems there isn't an easy fix and we can't use native "autoplay". What's a practical workaround then?

**Comment by courtsimas** [comment]
why is this issue closed? still an issue with my audio html element tests.

**Comment by bsoglin** [comment]
still an issue on Rails 8, turbo-rails `2.0.16`

**Comment by MSchmidt** [comment]
There is also an issue when visiting a page with an autoplay video via turbo. The video does not start to play automatically as I'd expect.

**Comment by elthariel** [comment]
@MSchmidt This is likely due to the browser heuristic to decide if a media can be autoplayed or not, not due to turbo rails. I have a turbo based app with autoplay and navigation + autoplay works fine on it

**Comment by elthariel** [comment]
Here comes a hacky workaround 😅:

```js
document.addEventListener('turbo:before-render', (event) => {
  let videos = document.querySelectorAll('video[autoplay]');
  for(let i = 0; i < videos.length; i++) {
    videos[i].autoplay = false;
  }
});
```

This disables the autoplay attribute on *all* videos with the autoplay attribute set before the page goes to cache. This implies the video won't autoplay again if the users comes on the page again from another link (or using navigation).

While this is good for my use case, it might not be what you want. In that case, remove the `autoplay` tag and use a stimulus controller to handle autoplay
